name: C++ Build on Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Install Requried Libs for FERS
      run: sudo apt-get install libboost-all-dev libfftw3-dev libhdf5-dev libhdf5-serial-dev build-essential cmake cmake-qt-gui python-all-dev libtinyxml-dev

    - name: Generate FERS
      run: |
        ls -a
        mkdir build
        cd build
        pwd # This will print the current working directory after cd
        ls -a 
        cmake .. -D FERS_LIB_HDF5="/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so" -D FERS_LIB_HDF5_HL="/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl.so" -D CMAKE_CXX_FLAGS="-I/usr/include/hdf5/serial/" 

    - name: Build FERS
      run: |
        cd build
        make

    - name: Install Requried Libs for validator
      run: sudo apt install libxerces-c-dev
    
    - name: Generate Validator
      run: |
        mkdir build
        cd build
        cmake 

    - name: Build Validator
      run: |
         cd build
         make
