name: C++ Build on Linux

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       
    - name: Checkout project and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Requried Libs
      run: sudo apt-get install libboost-all-dev libfftw3-dev libhdf5-dev libhdf5-serial-dev build-essential cmake cmake-qt-gui python-all-dev libtinyxml-dev

    - name: Generate
      run: |
        mkdir build
        cd build
        cmake -D FERS_LIB_HDF5="/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so" -D FERS_LIB_HDF5_HL="/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl.so" -D CMAKE_CXX_FLAGS="-I/usr/include/hdf5/serial/" ../

    - name: Build
      run: |
        cd build
        make

    - name: Prepare FERS for zip
      run: |
            mkdir ./toZip
            cp build/src/fers ./toZip/fers
    
    - name: Go nack to home
      run: cd ..

    - name: Install Requried Libs for validator
      run: sudo apt install libxerces-c-dev
  
    - name: Go to valifator and generate validator
      run: |
        cd config_validators
        mkdir build
        cd build
        cmake ..

    - name: Build Validator
      run: |
        cd config_validators/build
        make

    - name: Prepare Validator for zip
      run: |
            sudo cp config_validators/build/xml_validator_output ./toZip/xml_validator_output
            sudo cp config_validators/build/kml_visualiser ./toZip/kml_visualiser
            sudo cp config_validators/build/validator ./toZip/validator

    - name: Zip Docs and Build
      uses: TheDoctor0/zip-release@0.7.6
      with:
       directory: ./toZip # File to add to the archive
       path: ./*
       Filename: FERS.zip # The name of the archive file

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./toZip/FERS.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
