name: C++ Build on Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Install Requried Libs
      run: sudo apt-get install libboost-all-dev libfftw3-dev libhdf5-dev libhdf5-serial-dev build-essential cmake cmake-qt-gui python-all-dev libtinyxml-dev

    - name: Generate
      run: |
        mkdir build
        cd build
        cmake -D FERS_LIB_HDF5="/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so" -D FERS_LIB_HDF5_HL="/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl.so" -D CMAKE_CXX_FLAGS="-I/usr/include/hdf5/serial/" ../

    - name: Build
      run: |
        cd build
        make

    - name: Prepare for zip
      run: |
        mkdir build/toZip
        cp build/src/fers build/toZip/fers

    - name: Zip Docs and Build
      uses: TheDoctor0/zip-release@0.7.6
      with:
       directory: build/toZip # File to add to the archive
       path: ./*
       Filename: FERS.zip # The name of the archive file

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/toZip/FERS.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
